variables:
  app_name: "myapp"
  version: "1.0.0"

clients:
  mac_server:
    name: "mac_server"
    execution_method: ssh
    ssh_config:
      host: "192.168.0.199"
      port: 22
      username: "li"
      private_key_path: "/Users/li/.ssh/id_rsa"
      timeout_seconds: 2 

pipelines:
  - name: "local_and_remote_test"
    steps:
      - name: "local_step"
        script: "/Users/li/data/rust/ai-demo/scripts/test_capture_groups.sh"
        timeout_seconds: 5
        extract:
          - name: "os_version"
            patterns: ["OS Version: \\((.+)\\)"]
            source: "stdout"
          - name: "user_info"
            patterns: ["User: \\((.+?)\\)"]
            source: "stdout"
      
      - name: "remote_step"
        script: "/Users/li/data/rust/ai-demo/scripts/get_system_info.sh"
        timeout_seconds: 5
        servers:
          - mac_server
        extract:
          - name: "remote_os_version"
            patterns: ["OS Version: (.+)"]
            source: "stdout"
          - name: "remote_hostname"
            patterns: ["Hostname: (.+)"]
            source: "stdout"

default_timeout: 60 